openapi: 3.0.2
info:
  version: "1.0.0"
  title: sam2n
  description: OpenAPI specification for sam2n project
  contact:
    name: Nikolai Ischenko
    email: nik.ischenko@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8090
    description: Application which is deployed on the local machine
  - url: https://dev.byheart.run
    description: Application which is deployed on the local machine
paths:
  /v1/users:
    get:
      responses:
        '200':
          description: List of Users
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                description: Array with User object
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      description: User object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
          minLength: 2
          maxLength: 60
          example: John
        lastName:
          type: string
          minLength: 2
          maxLength: 60
          example: Smith
        address:
          $ref: '#/components/schemas/Address'
    
    Address:
      type: object
      properties:
        zipCode:
          type: string
          example: 2220008
        line1:
          type: string
          example: Madisson avenue, 234


